//
//  SchedulePresenter.swift
//  Planet365UIKit
//
//  Created by Vladimir Lukic on 19.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SchedulePresentationLogic
{
  func presentSomething(response: Schedule.Something.Response)
}

class SchedulePresenter: SchedulePresentationLogic
{
  weak var viewController: ScheduleDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Schedule.Something.Response)
  {
    let viewModel = Schedule.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
