//
//  MarcatoreInteractor.swift
//  Planet365UIKit
//
//  Created by Vladimir Lukic on 21.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MarcatoreBusinessLogic
{
    func handleAPI(request: Marcatore.API.Request)
}

protocol MarcatoreDataStore
{
    //var name: String { get set }
}

class MarcatoreInteractor: MarcatoreBusinessLogic, MarcatoreDataStore
{
    var presenter: MarcatorePresentationLogic?
    var worker: MarcatoreWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func handleAPI(request: Marcatore.API.Request) {
        
        // Load network request
        let seconds = 1.15
        DispatchQueue.main.asyncAfter(deadline: .now() + seconds) {
            
            // Get response from request
            let apiResponse = MoccupModel.API_RESPONSE
            
            // Call presenter
            self.presenter?.presentAPI(response: Marcatore.API.Response(response: apiResponse))
        }
        
    }
}
