//
//  HomeSoccerInteractor.swift
//  Planet365UIKit
//
//  Created by Vladimir Lukic on 19.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeSoccerBusinessLogic
{
    func handleInitControllers(request: HomeSoccer.InitControllers.Request)
    func handleControllersSwitch(request: HomeSoccer.Switch.Request)
}

protocol HomeSoccerDataStore
{
  //var name: String { get set }
}

class HomeSoccerInteractor: HomeSoccerBusinessLogic, HomeSoccerDataStore
{
    
    var presenter: HomeSoccerPresentationLogic?
    var worker: HomeSoccerWorker?
    //var name: String = ""
    
    // MARK: Switch controllers
    
    func handleInitControllers(request: HomeSoccer.InitControllers.Request) {
        presenter?.presentInitControllers(response: HomeSoccer.InitControllers.Response())
    }
    
    func handleControllersSwitch(request: HomeSoccer.Switch.Request) {
        presenter?.presentControllersSwitch(response: HomeSoccer.Switch.Response(indexSegmented: request.indexSegmented, indexHeader: request.indexHeader))
    }
}
