//
//  LivePresenter.swift
//  Planet365UIKit
//
//  Created by Vladimir Lukic on 19.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LivePresentationLogic
{
  func presentSomething(response: Live.Something.Response)
}

class LivePresenter: LivePresentationLogic
{
  weak var viewController: LiveDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Live.Something.Response)
  {
    let viewModel = Live.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
