//
//  NoDataPresenter.swift
//  Planet365UIKit
//
//  Created by Vladimir Lukic on 21.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NoDataPresentationLogic
{
  func presentSomething(response: NoData.Something.Response)
}

class NoDataPresenter: NoDataPresentationLogic
{
  weak var viewController: NoDataDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: NoData.Something.Response)
  {
    let viewModel = NoData.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
