//
//  HomeGameInteractor.swift
//  Planet365UIKit
//
//  Created by Vladimir Lukic on 22.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeGameBusinessLogic
{
  func doSomething(request: HomeGame.Something.Request)
}

protocol HomeGameDataStore
{
  //var name: String { get set }
}

class HomeGameInteractor: HomeGameBusinessLogic, HomeGameDataStore
{
  var presenter: HomeGamePresentationLogic?
  var worker: HomeGameWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: HomeGame.Something.Request)
  {
    worker = HomeGameWorker()
    worker?.doSomeWork()
    
    let response = HomeGame.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
