//
//  TabMenuContainerViewController.swift
//  Planet365UIKit
//
//  Created by Vladimir Lukic on 19.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabMenuContainerDisplayLogic: AnyObject
{
    // MARK: - List of ContainerViewController functions
    // MARK:
    
    func displayInitControllers(viewModel: TabMenuContainer.InitControllers.ViewModel)
    func displayTabButton(viewModel: TabMenuContainer.TabButton.ViewModel)
    func displayLoginUser(viewModel: TabMenuContainer.Login.ViewModel)
    func displayRegisterUser(viewModel: TabMenuContainer.Register.ViewModel)
}

class TabMenuContainerViewController: BaseViewController, TabMenuContainerDisplayLogic
{
    
    var interactor: TabMenuContainerBusinessLogic?
    var router: (NSObjectProtocol & TabMenuContainerRoutingLogic & TabMenuContainerDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = TabMenuContainerInteractor()
        let presenter = TabMenuContainerPresenter()
        let router = TabMenuContainerRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: Outlets
    
    ///
    // Header
    ///
    
    @IBOutlet weak var imgLogo: UIImageView!
    @IBOutlet weak var btnAccount: UIButton!
    
    ///
    // Nav header
    ///
    
    @IBOutlet weak var viewNavHeader: UIView!
    
    @IBOutlet weak var viewNavHeaderBtns: UIView!
    @IBOutlet weak var viewRegLoginActivityIndicator: UIView!
    @IBOutlet weak var btnRegister: UIButton!
    @IBOutlet weak var btnLogin: UIButton!
    
    @IBOutlet weak var viewNavHeaderTitle: UIView!
    @IBOutlet weak var lblNavHeaderTitle: UILabel!
    
    ///
    // Container
    ///
    
    // Main
    @IBOutlet weak var viewContent: UIView!
    
    // Tabs
    @IBOutlet weak var viewTabBar: UIView!
    @IBOutlet weak var viewTabBottom: UIView!
    @IBOutlet weak var viewTabBottomHeight: NSLayoutConstraint!
    
    // Container collections
    @IBOutlet var viewsTabContainer: [UIView]!
    @IBOutlet var imgsTabContainer: [UIImageView]!
    @IBOutlet var lblsTabContainer: [UILabel]!
    @IBOutlet var btnsTabContainer: [UIButton]!
    
    // MARK: - Properties
    // MARK:
    
    // Flags
    var isUserLogged: Bool = false
    
    // List of view controllers
    var homeViewController: UINavigationController!
    var liveViewController: UINavigationController!
    var scheduleViewController: UINavigationController!
    var myBetsViewController: UINavigationController!
    
    // Array that contains view controllers
    var viewControllers: [UINavigationController]!
    
    // Current selected index
    var selectedIndex:Int = 0
    var previousIndex:Int = -1
    
    var isFirstTimeLoaded = false
    
    // Notification names
    
    static let notification_tab_menu_back_button_handling = NSNotification.Name("notification_tab_menu_back_button_handling")
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        // Configure view
        configureView()
        
        // Load view controllers
        interactor?.handleViewControllerInitialisation(request: TabMenuContainer.InitControllers.Request())
    }
    
    // MARK: Configuration
    
    func configureView () {
        
        ///
        // Configure nav header
        ///
        ///
        self.viewNavHeader.backgroundColor = Color.backgroundGreyDark
        
        Utils.configureButton(button: btnRegister, title: nil, font: nil, titleColor: Color.foregroundWhite, titleColorHighlighted: nil, backgroundImage: nil)
        btnRegister.backgroundColor = Color.backgroundGreen
        btnRegister.layer.cornerRadius = 4.0
        btnRegister.layer.masksToBounds = true
        
        Utils.configureButton(button: btnLogin, title: nil, font: nil, titleColor: Color.foregroundWhite, titleColorHighlighted: nil, backgroundImage: nil)
        btnLogin.backgroundColor = Color.backgroundGreyLight
        btnLogin.layer.cornerRadius = 4.0
        btnLogin.layer.masksToBounds = true
        
        Utils.configureLabel(label: lblNavHeaderTitle, text: nil, font: nil, textColor: Color.foregroundWhite)
        
        showHideRegHeader()
        
        // Hide back button initially
        self.btnBack.alpha = 0.0
                
        // Render tab image as template to make them black
        for img in self.imgsTabContainer {
            img.backgroundColor = UIColor.clear
            
            let templateImage = img.image?.withRenderingMode(.alwaysTemplate)
            img.image = templateImage
            let templateHiglightedImage = img.highlightedImage?.withRenderingMode(.alwaysTemplate)
            img.highlightedImage = templateHiglightedImage
            img.tintColor = Color.foregroundBlack
        }
        
//        // Render button image as template to make them black
//        for btn in self.btnsTabContainer {
//            btn.backgroundColor = UIColor.clear
//
//            let templateImage = btn.image(for: .normal)?.withRenderingMode(.alwaysTemplate)
//            btn.setImage(templateImage, for: .normal)
//            let templateSelectedImage = btn.image(for: .selected)?.withRenderingMode(.alwaysTemplate)
//            btn.setImage(templateSelectedImage, for: .selected)
//            btn.tintColor = Color.foregroundBlack
//        }
    }
    
    // Show or hide nav header based on user status
    func showHideRegHeader() {
        if self.isUserLogged == true {
            self.viewNavHeaderTitle.alpha = 1.0
            self.viewNavHeaderBtns.alpha = 0.0
        } else {
            self.viewNavHeaderTitle.alpha = 0.0
            self.viewNavHeaderBtns.alpha = 1.0
        }
    }
    
    // Prepare onboarding
    func prepareOnboarding() {
        self.startActivityIndicator(onView: self.viewRegLoginActivityIndicator, color: Color.foregroundWhite)
        self.btnRegister.isEnabled = false
        self.btnLogin.isEnabled = false
    }
    
    // Finish onboarding
    func finishOnboarding() {
        self.viewRegLoginActivityIndicator.subviews.forEach({ $0.removeFromSuperview() })
        self.btnRegister.isEnabled = true
        self.btnLogin.isEnabled = true
        
        // Handle nav header
        self.showHideRegHeader()
    }
    
    // MARK: Button actions
    
    // Open Account section
    @IBAction func openAccountSection(_ sender: UIButton) {
        self.pushToViewController(vc: "AccountViewController", storyboardName: "Account", params: nil)
    }
    
    // Override go back function to pop the appropriate controller
    override func goBack(sender: UIButton) {
        viewControllers[selectedIndex].popViewController(animated: true)
        handleBackButton()
    }
    
    // Handle register button tap
    @IBAction func registerButtonTapped(_ sender: UIButton) {
        prepareOnboarding()
        interactor?.handleRegisterUser(request: TabMenuContainer.Register.Request())
        // Should open some modal screen instead
    }
    
    // Handle login button tap
    @IBAction func loginButtonTapped(_ sender: UIButton) {
        prepareOnboarding()
        interactor?.handleLoginUser(request: TabMenuContainer.Login.Request())
        // Should open some modal screen instead
    }
        
    // Handle tab button tap
    @IBAction func containerButtonTapped(_ sender: UIButton) {
        interactor?.handleTabBarButtons(request: TabMenuContainer.TabButton.Request(sender: sender))
    }
    
    // MARK: - Implement display functions
    // MARK:
    
    func displayInitControllers(viewModel: TabMenuContainer.InitControllers.ViewModel) {
        
        // Get storyboards
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        
        // Get view controllers
        
        homeViewController = storyboard.instantiateViewController(withIdentifier: "HomeNavigationView") as? UINavigationController
        liveViewController = storyboard.instantiateViewController(withIdentifier: "LiveNavigationView") as? UINavigationController
        scheduleViewController = storyboard.instantiateViewController(withIdentifier: "ScheduleNavigationView") as? UINavigationController
        myBetsViewController = storyboard.instantiateViewController(withIdentifier: "MyBetsNavigationView") as? UINavigationController
        
        // Save instantiated references in array
        viewControllers = [homeViewController, liveViewController, scheduleViewController, myBetsViewController]
        
        // Set initial vc
        containerButtonTapped(btnsTabContainer[0])
    }
    
    // MARK: Tab bar buttons handling
    
    func displayTabButton(viewModel: TabMenuContainer.TabButton.ViewModel) {
        
        // Index already selected
        if selectedIndex == viewModel.sender.tag && isFirstTimeLoaded == true {
            return
        }
        isFirstTimeLoaded = true
        
        // Update indexes
        previousIndex = selectedIndex
        selectedIndex = viewModel.sender.tag
        
        // Unselect current button
        btnsTabContainer[previousIndex].isSelected = false
        viewsTabContainer[previousIndex].alpha = 1.0
        imgsTabContainer[previousIndex].isHighlighted = false
        
        // Get and remove previous view controller
        let previousVC = viewControllers[previousIndex]
        previousVC.willMove(toParent: nil)
        previousVC.view.removeFromSuperview()
        previousVC.removeFromParent()
        
        // Select tapped button
        viewModel.sender.isSelected = true
        viewsTabContainer[selectedIndex].alpha = 1.0
        imgsTabContainer[selectedIndex].isHighlighted = true
        
        // Get and add next view controller
        let vc = viewControllers[selectedIndex]
        addChild(vc)
        vc.view.frame = viewContent.bounds
        viewContent.addSubview(vc.view)
        vc.didMove(toParent: self)
        
        // Update back button
        self.handleBackButton()
    }
    
    // MARK: Onboarding handling
    
    func displayLoginUser(viewModel: TabMenuContainer.Login.ViewModel) {
        DispatchQueue.main.async {
            self.isUserLogged = true
            self.finishOnboarding()
        }
    }
    
    func displayRegisterUser(viewModel: TabMenuContainer.Register.ViewModel) {
        DispatchQueue.main.async {
            self.isUserLogged = true
            self.finishOnboarding()
        }
    }
    
    // MARK: - Back button handling
    // MARK:
    
    @objc func handleBackButton() {
        
        // Check number of view controllers
        UIView.animate(withDuration: 0.33, delay: 0.0, options: .transitionCrossDissolve) {
            if self.viewControllers[self.selectedIndex].viewControllers.count > 1 {
                self.btnBack.alpha = 1.0
            } else {
                self.btnBack.alpha = 0.0
            }
        } completion: { completed in
            // do nothin'
        }
    }
    
    // MARK: - Notification handling
    // MARK:
    
    override func registerForNotifications() {
        super.registerForNotifications()
        
        NotificationCenter.default.addObserver(self, selector: #selector(handleBackButton), name: TabMenuContainerViewController.notification_tab_menu_back_button_handling, object: nil)
    }
    
    override func unregisterForNotifications() {
        NotificationCenter.default.removeObserver(self, name: TabMenuContainerViewController.notification_tab_menu_back_button_handling, object: nil)
        
        super.unregisterForNotifications()
    }
}
