//
//  TabMenuContainerInteractor.swift
//  Planet365UIKit
//
//  Created by Vladimir Lukic on 19.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabMenuContainerBusinessLogic
{
    // List of ContainerInteractor functions
    func handleViewControllerInitialisation(request: TabMenuContainer.InitControllers.Request)
    func handleTabBarButtons(request: TabMenuContainer.TabButton.Request)
    func handleLoginUser(request: TabMenuContainer.Login.Request)
    func handleRegisterUser(request: TabMenuContainer.Register.Request)
}

protocol TabMenuContainerDataStore
{
    //var name: String { get set }
}

class TabMenuContainerInteractor: TabMenuContainerBusinessLogic, TabMenuContainerDataStore
{
    var presenter: TabMenuContainerPresentationLogic?
    var worker: TabMenuContainerWorker?
    //var name: String = ""
    
    // MARK: - Implement interactor functions
    // MARK:
    
    // MARK: View controller initialisation
    
    func handleViewControllerInitialisation(request: TabMenuContainer.InitControllers.Request) {
        presenter?.presentViewControllerInitialisation(response: TabMenuContainer.InitControllers.Response())
    }
    
    // MARK: Tab bar buttons handling
    
    func handleTabBarButtons(request: TabMenuContainer.TabButton.Request) {
        presenter?.presentTabBarButtons(response: TabMenuContainer.TabButton.Response(sender: request.sender))
    }
    
    // MARK: Login user
    
    func handleLoginUser(request: TabMenuContainer.Login.Request) {
        let seconds = 3.5
        DispatchQueue.global().asyncAfter(deadline: .now() + seconds) { // Do some networking
            self.presenter?.presentLoginUser(response: TabMenuContainer.Login.Response())
        }
        
    }
    
    // MARK: Register user
    
    func handleRegisterUser(request: TabMenuContainer.Register.Request) {
        let seconds = 3.5
        DispatchQueue.global().asyncAfter(deadline: .now() + seconds) { // Do some networking
            self.presenter?.presentRegisterUser(response: TabMenuContainer.Register.Response())
        }
        
    }
}
