//
//  HomeNFLInteractor.swift
//  Planet365UIKit
//
//  Created by Vladimir Lukic on 19.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeNFLBusinessLogic
{
  func doSomething(request: HomeNFL.Something.Request)
}

protocol HomeNFLDataStore
{
  //var name: String { get set }
}

class HomeNFLInteractor: HomeNFLBusinessLogic, HomeNFLDataStore
{
  var presenter: HomeNFLPresentationLogic?
  var worker: HomeNFLWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: HomeNFL.Something.Request)
  {
    worker = HomeNFLWorker()
    worker?.doSomeWork()
    
    let response = HomeNFL.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
