//
//  HomeNFLPresenter.swift
//  Planet365UIKit
//
//  Created by Vladimir Lukic on 19.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeNFLPresentationLogic
{
  func presentSomething(response: HomeNFL.Something.Response)
}

class HomeNFLPresenter: HomeNFLPresentationLogic
{
  weak var viewController: HomeNFLDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: HomeNFL.Something.Response)
  {
    let viewModel = HomeNFL.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
