//
//  MyBetsPresenter.swift
//  Planet365UIKit
//
//  Created by Vladimir Lukic on 19.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyBetsPresentationLogic
{
  func presentSomething(response: MyBets.Something.Response)
}

class MyBetsPresenter: MyBetsPresentationLogic
{
  weak var viewController: MyBetsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MyBets.Something.Response)
  {
    let viewModel = MyBets.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
