//
//  HomePlayerInteractor.swift
//  Planet365UIKit
//
//  Created by Vladimir Lukic on 22.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePlayerBusinessLogic
{
  func doSomething(request: HomePlayer.Something.Request)
}

protocol HomePlayerDataStore
{
  //var name: String { get set }
}

class HomePlayerInteractor: HomePlayerBusinessLogic, HomePlayerDataStore
{
  var presenter: HomePlayerPresentationLogic?
  var worker: HomePlayerWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: HomePlayer.Something.Request)
  {
    worker = HomePlayerWorker()
    worker?.doSomeWork()
    
    let response = HomePlayer.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
